const actionTypes = {
  FLIP_ONE_CARD: 'FLIP_ONE_CARD',
  FLIP_TWO_CARD: 'FLIP_TWO_CARD',
  FLIP_THREE_CARD: 'FLIP_THREE_CARD',
  FLIP_ALL_CARD: 'FLIP_ALL_CARD',
  SWAP_CARDS: 'SWAP_CARDS',
  CHECK_CARDS: 'CHECK_CARDS',
  SET_COUNT: 'SET_COUNT',
};

export default actionTypes;
