export default {
  cards: [
    { id: 1, logo: 1, cardFace: false, complete: false },
    { id: 2, logo: 2, cardFace: false, complete: false },

    { id: 19, logo: 1, cardFace: false, complete: false },
    { id: 20, logo: 2, cardFace: false, complete: false },
  ],
};

// export default {
//   cards: [
//     { id: 1, logo: 1, cardFace: false, complete: false },
//     { id: 2, logo: 2, cardFace: false, complete: false },
//     { id: 3, logo: 3, cardFace: false, complete: false },
//     { id: 4, logo: 4, cardFace: false, complete: false },
//     { id: 5, logo: 5, cardFace: false, complete: false },
//     { id: 6, logo: 6, cardFace: false, complete: false },
//     { id: 7, logo: 7, cardFace: false, complete: false },
//     { id: 8, logo: 8, cardFace: false, complete: false },
//     { id: 9, logo: 9, cardFace: false, complete: false },
//     { id: 10, logo: 10, cardFace: false, complete: false },
//     { id: 11, logo: 11, cardFace: false, complete: false },
//     { id: 12, logo: 12, cardFace: false, complete: false },
//     { id: 13, logo: 13, cardFace: false, complete: false },
//     { id: 14, logo: 14, cardFace: false, complete: false },
//     { id: 15, logo: 15, cardFace: false, complete: false },
//     { id: 16, logo: 16, cardFace: false, complete: false },
//     { id: 17, logo: 17, cardFace: false, complete: false },
//     { id: 18, logo: 18, cardFace: false, complete: false },
//     { id: 19, logo: 1, cardFace: false, complete: false },
//     { id: 20, logo: 2, cardFace: false, complete: false },
//     { id: 21, logo: 3, cardFace: false, complete: false },
//     { id: 22, logo: 4, cardFace: false, complete: false },
//     { id: 23, logo: 5, cardFace: false, complete: false },
//     { id: 24, logo: 6, cardFace: false, complete: false },
//     { id: 25, logo: 7, cardFace: false, complete: false },
//     { id: 26, logo: 8, cardFace: false, complete: false },
//     { id: 27, logo: 9, cardFace: false, complete: false },
//     { id: 28, logo: 10, cardFace: false, complete: false },
//     { id: 29, logo: 11, cardFace: false, complete: false },
//     { id: 30, logo: 12, cardFace: false, complete: false },
//     { id: 31, logo: 13, cardFace: false, complete: false },
//     { id: 32, logo: 14, cardFace: false, complete: false },
//     { id: 33, logo: 15, cardFace: false, complete: false },
//     { id: 34, logo: 16, cardFace: false, complete: false },
//     { id: 35, logo: 17, cardFace: false, complete: false },
//     { id: 36, logo: 18, cardFace: false, complete: false },
//   ],
// };
